name: Stage the app

on: 
  pull_request:
    types: [labeled]
    
    
env:
  DOCKER_IMAGE_NAME: jalcantara90-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: pcghverificationdev
    
jobs:
  build:
    runs-on: ubuntu-latest
